package ar.com.rollpaper.pricing.beans.rpdb;
// Generated 17/05/2018 18:21:20 by Hibernate Tools 5.3.0.Beta2

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * CcobClie generated by hbm2java
 */
public class CcobClie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int clieCliente;
	private String clieNombre;
	private String clieNombreLegal;
	private boolean clieEsCliGlob;
	private String clieDomicilio;
	private String clieLocalidad;
	private String clieCodPostal;
	private String clieProvincia;
	private String cliePais;
	private String clieTelefono;
	private String clieFax;
	private String clieEmail;
	private String clieObservacion;
	private String clieCodProveedor;
	private String clieReferencia;
	private String clieHoraAtencion;
	private String clieHoraEntrega;
	private String clieCondicionIva;
	private String clieCuit;
	private String clieIngBrutos;
	private String clieContacVenta;
	private String clieContacCobro;
	private String clieCondPago;
	private String clieMonedaCte;
	private String clieCuentaClie;
	private String clieTipoCli;
	private String clieActividadCli;
	private String clieClasif1;
	private String clieClasif2;
	private String clieClasif3;
	private String clieClasif4;
	private String clieVendedor;
	private String clieZonaVenta;
	private String clieCobrador;
	private String clieFlete;
	private boolean clieBloqueadoPed;
	private boolean clieBloqueadoFac;
	private Date clieFechaAlta;
	private Date clieFechaBaja;
	private boolean clieHabilWeb;
	private String cliePasswordWeb;
	private String clieFormatoFimc;
	private String clieVendedor2;
	private String clieString1;
	private String clieString2;
	private String clieString3;
	private String clieString4;
	private Date clieFecha1;
	private Date clieFecha2;
	private Date clieFecha3;
	private Date clieFecha4;
	private String clieClasifNpcv1;
	private String clieClasifNpcv2;
	private String clieClasifNpcv3;
	private String clieClasifNpcv4;
	private String clieClasifNpcv5;
	private String clieClasifNpcv6;
	private boolean clieHabilCcClie;
	private String clieClienteExt;
	private Date clieFechaProxGc;
	private String clieProxGesCobr;
	private short clieAcctGencbpte;
	private String clieNodoOrigen;
	private String clieMunicipio;
	private boolean clieInfTabasto;
	private boolean clieCobroCorrel;
	private String clieVehiculo;
	private String clieDistribuidor;
	private String clieZonaDistrib;
	private String clieCalle;
	private Integer clieNroCalle;
	private String cliePiso;
	private String clieDepto;
	private String clieBarrio;
	private short clieDiasgrAtrRc;
	private String clieClasif5;
	private String clieClasif6;
	private String clieClasif7;
	private String clieClasif8;
	private String clieClasif9;
	private String clieSitioWeb;
	//private Serializable clieDescripActiv;
	private Integer clieFactAnual;
	private Integer clieCantEmplead;
	private String clieEcmEmail;
	private String clieEcmAsunto;
	//private Serializable clieEcmCuerpo;
	//private Serializable clieObservacionProxGesCobr;
	private String clieCodCalle;
	private String clieErmEmail;
	private String clieErmAsunto;
	private Serializable clieErmCuerpo;
	private BigDecimal clieTasaMensInteres;
	private Date clieHoraProxGc;
	private Short clieNivelAccesoWeb;
	private byte clieBloqueadoReservas;
	private String clieLogotipoNomOri;
	private String clieLogotipoNomAlmac;

	public CcobClie() {
	}

	public CcobClie(int clieCliente, String clieNombre, String clieNombreLegal, boolean clieEsCliGlob,
			String clieProvincia, String cliePais, String clieCondicionIva, String clieCondPago, String clieMonedaCte,
			String clieCuentaClie, String clieTipoCli, String clieActividadCli, String clieVendedor,
			String clieZonaVenta, String clieCobrador, String clieFlete, boolean clieBloqueadoPed,
			boolean clieBloqueadoFac, Date clieFechaAlta, boolean clieHabilWeb, boolean clieHabilCcClie,
			short clieAcctGencbpte, boolean clieInfTabasto, boolean clieCobroCorrel, short clieDiasgrAtrRc,
			byte clieBloqueadoReservas) {
		this.clieCliente = clieCliente;
		this.clieNombre = clieNombre;
		this.clieNombreLegal = clieNombreLegal;
		this.clieEsCliGlob = clieEsCliGlob;
		this.clieProvincia = clieProvincia;
		this.cliePais = cliePais;
		this.clieCondicionIva = clieCondicionIva;
		this.clieCondPago = clieCondPago;
		this.clieMonedaCte = clieMonedaCte;
		this.clieCuentaClie = clieCuentaClie;
		this.clieTipoCli = clieTipoCli;
		this.clieActividadCli = clieActividadCli;
		this.clieVendedor = clieVendedor;
		this.clieZonaVenta = clieZonaVenta;
		this.clieCobrador = clieCobrador;
		this.clieFlete = clieFlete;
		this.clieBloqueadoPed = clieBloqueadoPed;
		this.clieBloqueadoFac = clieBloqueadoFac;
		this.clieFechaAlta = clieFechaAlta;
		this.clieHabilWeb = clieHabilWeb;
		this.clieHabilCcClie = clieHabilCcClie;
		this.clieAcctGencbpte = clieAcctGencbpte;
		this.clieInfTabasto = clieInfTabasto;
		this.clieCobroCorrel = clieCobroCorrel;
		this.clieDiasgrAtrRc = clieDiasgrAtrRc;
		this.clieBloqueadoReservas = clieBloqueadoReservas;
	}

	public CcobClie(int clieCliente, String clieNombre, String clieNombreLegal, boolean clieEsCliGlob,
			String clieDomicilio, String clieLocalidad, String clieCodPostal, String clieProvincia, String cliePais,
			String clieTelefono, String clieFax, String clieEmail, String clieObservacion, String clieCodProveedor,
			String clieReferencia, String clieHoraAtencion, String clieHoraEntrega, String clieCondicionIva,
			String clieCuit, String clieIngBrutos, String clieContacVenta, String clieContacCobro, String clieCondPago,
			String clieMonedaCte, String clieCuentaClie, String clieTipoCli, String clieActividadCli,
			String clieClasif1, String clieClasif2, String clieClasif3, String clieClasif4, String clieVendedor,
			String clieZonaVenta, String clieCobrador, String clieFlete, boolean clieBloqueadoPed,
			boolean clieBloqueadoFac, Date clieFechaAlta, Date clieFechaBaja, boolean clieHabilWeb,
			String cliePasswordWeb, String clieFormatoFimc, String clieVendedor2, String clieString1,
			String clieString2, String clieString3, String clieString4, Date clieFecha1, Date clieFecha2,
			Date clieFecha3, Date clieFecha4, String clieClasifNpcv1, String clieClasifNpcv2, String clieClasifNpcv3,
			String clieClasifNpcv4, String clieClasifNpcv5, String clieClasifNpcv6, boolean clieHabilCcClie,
			String clieClienteExt, Date clieFechaProxGc, String clieProxGesCobr, short clieAcctGencbpte,
			String clieNodoOrigen, String clieMunicipio, boolean clieInfTabasto, boolean clieCobroCorrel,
			String clieVehiculo, String clieDistribuidor, String clieZonaDistrib, String clieCalle,
			Integer clieNroCalle, String cliePiso, String clieDepto, String clieBarrio, short clieDiasgrAtrRc,
			String clieClasif5, String clieClasif6, String clieClasif7, String clieClasif8, String clieClasif9,
			String clieSitioWeb, Serializable clieDescripActiv, Integer clieFactAnual, Integer clieCantEmplead,
			String clieEcmEmail, String clieEcmAsunto, Serializable clieEcmCuerpo,
			Serializable clieObservacionProxGesCobr, String clieCodCalle, String clieErmEmail, String clieErmAsunto,
			Serializable clieErmCuerpo, BigDecimal clieTasaMensInteres, Date clieHoraProxGc, Short clieNivelAccesoWeb,
			byte clieBloqueadoReservas, String clieLogotipoNomOri, String clieLogotipoNomAlmac) {
		this.clieCliente = clieCliente;
		this.clieNombre = clieNombre;
		this.clieNombreLegal = clieNombreLegal;
		this.clieEsCliGlob = clieEsCliGlob;
		this.clieDomicilio = clieDomicilio;
		this.clieLocalidad = clieLocalidad;
		this.clieCodPostal = clieCodPostal;
		this.clieProvincia = clieProvincia;
		this.cliePais = cliePais;
		this.clieTelefono = clieTelefono;
		this.clieFax = clieFax;
		this.clieEmail = clieEmail;
		this.clieObservacion = clieObservacion;
		this.clieCodProveedor = clieCodProveedor;
		this.clieReferencia = clieReferencia;
		this.clieHoraAtencion = clieHoraAtencion;
		this.clieHoraEntrega = clieHoraEntrega;
		this.clieCondicionIva = clieCondicionIva;
		this.clieCuit = clieCuit;
		this.clieIngBrutos = clieIngBrutos;
		this.clieContacVenta = clieContacVenta;
		this.clieContacCobro = clieContacCobro;
		this.clieCondPago = clieCondPago;
		this.clieMonedaCte = clieMonedaCte;
		this.clieCuentaClie = clieCuentaClie;
		this.clieTipoCli = clieTipoCli;
		this.clieActividadCli = clieActividadCli;
		this.clieClasif1 = clieClasif1;
		this.clieClasif2 = clieClasif2;
		this.clieClasif3 = clieClasif3;
		this.clieClasif4 = clieClasif4;
		this.clieVendedor = clieVendedor;
		this.clieZonaVenta = clieZonaVenta;
		this.clieCobrador = clieCobrador;
		this.clieFlete = clieFlete;
		this.clieBloqueadoPed = clieBloqueadoPed;
		this.clieBloqueadoFac = clieBloqueadoFac;
		this.clieFechaAlta = clieFechaAlta;
		this.clieFechaBaja = clieFechaBaja;
		this.clieHabilWeb = clieHabilWeb;
		this.cliePasswordWeb = cliePasswordWeb;
		this.clieFormatoFimc = clieFormatoFimc;
		this.clieVendedor2 = clieVendedor2;
		this.clieString1 = clieString1;
		this.clieString2 = clieString2;
		this.clieString3 = clieString3;
		this.clieString4 = clieString4;
		this.clieFecha1 = clieFecha1;
		this.clieFecha2 = clieFecha2;
		this.clieFecha3 = clieFecha3;
		this.clieFecha4 = clieFecha4;
		this.clieClasifNpcv1 = clieClasifNpcv1;
		this.clieClasifNpcv2 = clieClasifNpcv2;
		this.clieClasifNpcv3 = clieClasifNpcv3;
		this.clieClasifNpcv4 = clieClasifNpcv4;
		this.clieClasifNpcv5 = clieClasifNpcv5;
		this.clieClasifNpcv6 = clieClasifNpcv6;
		this.clieHabilCcClie = clieHabilCcClie;
		this.clieClienteExt = clieClienteExt;
		this.clieFechaProxGc = clieFechaProxGc;
		this.clieProxGesCobr = clieProxGesCobr;
		this.clieAcctGencbpte = clieAcctGencbpte;
		this.clieNodoOrigen = clieNodoOrigen;
		this.clieMunicipio = clieMunicipio;
		this.clieInfTabasto = clieInfTabasto;
		this.clieCobroCorrel = clieCobroCorrel;
		this.clieVehiculo = clieVehiculo;
		this.clieDistribuidor = clieDistribuidor;
		this.clieZonaDistrib = clieZonaDistrib;
		this.clieCalle = clieCalle;
		this.clieNroCalle = clieNroCalle;
		this.cliePiso = cliePiso;
		this.clieDepto = clieDepto;
		this.clieBarrio = clieBarrio;
		this.clieDiasgrAtrRc = clieDiasgrAtrRc;
		this.clieClasif5 = clieClasif5;
		this.clieClasif6 = clieClasif6;
		this.clieClasif7 = clieClasif7;
		this.clieClasif8 = clieClasif8;
		this.clieClasif9 = clieClasif9;
		this.clieSitioWeb = clieSitioWeb;
	//	this.clieDescripActiv = clieDescripActiv;
		this.clieFactAnual = clieFactAnual;
		this.clieCantEmplead = clieCantEmplead;
		this.clieEcmEmail = clieEcmEmail;
		this.clieEcmAsunto = clieEcmAsunto;
	//	this.clieEcmCuerpo = clieEcmCuerpo;
	//	this.clieObservacionProxGesCobr = clieObservacionProxGesCobr;
		this.clieCodCalle = clieCodCalle;
		this.clieErmEmail = clieErmEmail;
		this.clieErmAsunto = clieErmAsunto;
		this.clieErmCuerpo = clieErmCuerpo;
		this.clieTasaMensInteres = clieTasaMensInteres;
		this.clieHoraProxGc = clieHoraProxGc;
		this.clieNivelAccesoWeb = clieNivelAccesoWeb;
		this.clieBloqueadoReservas = clieBloqueadoReservas;
		this.clieLogotipoNomOri = clieLogotipoNomOri;
		this.clieLogotipoNomAlmac = clieLogotipoNomAlmac;
	}

	public int getClieCliente() {
		return this.clieCliente;
	}

	public void setClieCliente(int clieCliente) {
		this.clieCliente = clieCliente;
	}

	public String getClieNombre() {
		return this.clieNombre;
	}

	public void setClieNombre(String clieNombre) {
		this.clieNombre = clieNombre;
	}

	public String getClieNombreLegal() {
		return this.clieNombreLegal;
	}

	public void setClieNombreLegal(String clieNombreLegal) {
		this.clieNombreLegal = clieNombreLegal;
	}

	public boolean isClieEsCliGlob() {
		return this.clieEsCliGlob;
	}

	public void setClieEsCliGlob(boolean clieEsCliGlob) {
		this.clieEsCliGlob = clieEsCliGlob;
	}

	public String getClieDomicilio() {
		return this.clieDomicilio;
	}

	public void setClieDomicilio(String clieDomicilio) {
		this.clieDomicilio = clieDomicilio;
	}

	public String getClieLocalidad() {
		return this.clieLocalidad;
	}

	public void setClieLocalidad(String clieLocalidad) {
		this.clieLocalidad = clieLocalidad;
	}

	public String getClieCodPostal() {
		return this.clieCodPostal;
	}

	public void setClieCodPostal(String clieCodPostal) {
		this.clieCodPostal = clieCodPostal;
	}

	public String getClieProvincia() {
		return this.clieProvincia;
	}

	public void setClieProvincia(String clieProvincia) {
		this.clieProvincia = clieProvincia;
	}

	public String getCliePais() {
		return this.cliePais;
	}

	public void setCliePais(String cliePais) {
		this.cliePais = cliePais;
	}

	public String getClieTelefono() {
		return this.clieTelefono;
	}

	public void setClieTelefono(String clieTelefono) {
		this.clieTelefono = clieTelefono;
	}

	public String getClieFax() {
		return this.clieFax;
	}

	public void setClieFax(String clieFax) {
		this.clieFax = clieFax;
	}

	public String getClieEmail() {
		return this.clieEmail;
	}

	public void setClieEmail(String clieEmail) {
		this.clieEmail = clieEmail;
	}

	public String getClieObservacion() {
		return this.clieObservacion;
	}

	public void setClieObservacion(String clieObservacion) {
		this.clieObservacion = clieObservacion;
	}

	public String getClieCodProveedor() {
		return this.clieCodProveedor;
	}

	public void setClieCodProveedor(String clieCodProveedor) {
		this.clieCodProveedor = clieCodProveedor;
	}

	public String getClieReferencia() {
		return this.clieReferencia;
	}

	public void setClieReferencia(String clieReferencia) {
		this.clieReferencia = clieReferencia;
	}

	public String getClieHoraAtencion() {
		return this.clieHoraAtencion;
	}

	public void setClieHoraAtencion(String clieHoraAtencion) {
		this.clieHoraAtencion = clieHoraAtencion;
	}

	public String getClieHoraEntrega() {
		return this.clieHoraEntrega;
	}

	public void setClieHoraEntrega(String clieHoraEntrega) {
		this.clieHoraEntrega = clieHoraEntrega;
	}

	public String getClieCondicionIva() {
		return this.clieCondicionIva;
	}

	public void setClieCondicionIva(String clieCondicionIva) {
		this.clieCondicionIva = clieCondicionIva;
	}

	public String getClieCuit() {
		return this.clieCuit;
	}

	public void setClieCuit(String clieCuit) {
		this.clieCuit = clieCuit;
	}

	public String getClieIngBrutos() {
		return this.clieIngBrutos;
	}

	public void setClieIngBrutos(String clieIngBrutos) {
		this.clieIngBrutos = clieIngBrutos;
	}

	public String getClieContacVenta() {
		return this.clieContacVenta;
	}

	public void setClieContacVenta(String clieContacVenta) {
		this.clieContacVenta = clieContacVenta;
	}

	public String getClieContacCobro() {
		return this.clieContacCobro;
	}

	public void setClieContacCobro(String clieContacCobro) {
		this.clieContacCobro = clieContacCobro;
	}

	public String getClieCondPago() {
		return this.clieCondPago;
	}

	public void setClieCondPago(String clieCondPago) {
		this.clieCondPago = clieCondPago;
	}

	public String getClieMonedaCte() {
		return this.clieMonedaCte;
	}

	public void setClieMonedaCte(String clieMonedaCte) {
		this.clieMonedaCte = clieMonedaCte;
	}

	public String getClieCuentaClie() {
		return this.clieCuentaClie;
	}

	public void setClieCuentaClie(String clieCuentaClie) {
		this.clieCuentaClie = clieCuentaClie;
	}

	public String getClieTipoCli() {
		return this.clieTipoCli;
	}

	public void setClieTipoCli(String clieTipoCli) {
		this.clieTipoCli = clieTipoCli;
	}

	public String getClieActividadCli() {
		return this.clieActividadCli;
	}

	public void setClieActividadCli(String clieActividadCli) {
		this.clieActividadCli = clieActividadCli;
	}

	public String getClieClasif1() {
		return this.clieClasif1;
	}

	public void setClieClasif1(String clieClasif1) {
		this.clieClasif1 = clieClasif1;
	}

	public String getClieClasif2() {
		return this.clieClasif2;
	}

	public void setClieClasif2(String clieClasif2) {
		this.clieClasif2 = clieClasif2;
	}

	public String getClieClasif3() {
		return this.clieClasif3;
	}

	public void setClieClasif3(String clieClasif3) {
		this.clieClasif3 = clieClasif3;
	}

	public String getClieClasif4() {
		return this.clieClasif4;
	}

	public void setClieClasif4(String clieClasif4) {
		this.clieClasif4 = clieClasif4;
	}

	public String getClieVendedor() {
		return this.clieVendedor;
	}

	public void setClieVendedor(String clieVendedor) {
		this.clieVendedor = clieVendedor;
	}

	public String getClieZonaVenta() {
		return this.clieZonaVenta;
	}

	public void setClieZonaVenta(String clieZonaVenta) {
		this.clieZonaVenta = clieZonaVenta;
	}

	public String getClieCobrador() {
		return this.clieCobrador;
	}

	public void setClieCobrador(String clieCobrador) {
		this.clieCobrador = clieCobrador;
	}

	public String getClieFlete() {
		return this.clieFlete;
	}

	public void setClieFlete(String clieFlete) {
		this.clieFlete = clieFlete;
	}

	public boolean isClieBloqueadoPed() {
		return this.clieBloqueadoPed;
	}

	public void setClieBloqueadoPed(boolean clieBloqueadoPed) {
		this.clieBloqueadoPed = clieBloqueadoPed;
	}

	public boolean isClieBloqueadoFac() {
		return this.clieBloqueadoFac;
	}

	public void setClieBloqueadoFac(boolean clieBloqueadoFac) {
		this.clieBloqueadoFac = clieBloqueadoFac;
	}

	public Date getClieFechaAlta() {
		return this.clieFechaAlta;
	}

	public void setClieFechaAlta(Date clieFechaAlta) {
		this.clieFechaAlta = clieFechaAlta;
	}

	public Date getClieFechaBaja() {
		return this.clieFechaBaja;
	}

	public void setClieFechaBaja(Date clieFechaBaja) {
		this.clieFechaBaja = clieFechaBaja;
	}

	public boolean isClieHabilWeb() {
		return this.clieHabilWeb;
	}

	public void setClieHabilWeb(boolean clieHabilWeb) {
		this.clieHabilWeb = clieHabilWeb;
	}

	public String getCliePasswordWeb() {
		return this.cliePasswordWeb;
	}

	public void setCliePasswordWeb(String cliePasswordWeb) {
		this.cliePasswordWeb = cliePasswordWeb;
	}

	public String getClieFormatoFimc() {
		return this.clieFormatoFimc;
	}

	public void setClieFormatoFimc(String clieFormatoFimc) {
		this.clieFormatoFimc = clieFormatoFimc;
	}

	public String getClieVendedor2() {
		return this.clieVendedor2;
	}

	public void setClieVendedor2(String clieVendedor2) {
		this.clieVendedor2 = clieVendedor2;
	}

	public String getClieString1() {
		return this.clieString1;
	}

	public void setClieString1(String clieString1) {
		this.clieString1 = clieString1;
	}

	public String getClieString2() {
		return this.clieString2;
	}

	public void setClieString2(String clieString2) {
		this.clieString2 = clieString2;
	}

	public String getClieString3() {
		return this.clieString3;
	}

	public void setClieString3(String clieString3) {
		this.clieString3 = clieString3;
	}

	public String getClieString4() {
		return this.clieString4;
	}

	public void setClieString4(String clieString4) {
		this.clieString4 = clieString4;
	}

	public Date getClieFecha1() {
		return this.clieFecha1;
	}

	public void setClieFecha1(Date clieFecha1) {
		this.clieFecha1 = clieFecha1;
	}

	public Date getClieFecha2() {
		return this.clieFecha2;
	}

	public void setClieFecha2(Date clieFecha2) {
		this.clieFecha2 = clieFecha2;
	}

	public Date getClieFecha3() {
		return this.clieFecha3;
	}

	public void setClieFecha3(Date clieFecha3) {
		this.clieFecha3 = clieFecha3;
	}

	public Date getClieFecha4() {
		return this.clieFecha4;
	}

	public void setClieFecha4(Date clieFecha4) {
		this.clieFecha4 = clieFecha4;
	}

	public String getClieClasifNpcv1() {
		return this.clieClasifNpcv1;
	}

	public void setClieClasifNpcv1(String clieClasifNpcv1) {
		this.clieClasifNpcv1 = clieClasifNpcv1;
	}

	public String getClieClasifNpcv2() {
		return this.clieClasifNpcv2;
	}

	public void setClieClasifNpcv2(String clieClasifNpcv2) {
		this.clieClasifNpcv2 = clieClasifNpcv2;
	}

	public String getClieClasifNpcv3() {
		return this.clieClasifNpcv3;
	}

	public void setClieClasifNpcv3(String clieClasifNpcv3) {
		this.clieClasifNpcv3 = clieClasifNpcv3;
	}

	public String getClieClasifNpcv4() {
		return this.clieClasifNpcv4;
	}

	public void setClieClasifNpcv4(String clieClasifNpcv4) {
		this.clieClasifNpcv4 = clieClasifNpcv4;
	}

	public String getClieClasifNpcv5() {
		return this.clieClasifNpcv5;
	}

	public void setClieClasifNpcv5(String clieClasifNpcv5) {
		this.clieClasifNpcv5 = clieClasifNpcv5;
	}

	public String getClieClasifNpcv6() {
		return this.clieClasifNpcv6;
	}

	public void setClieClasifNpcv6(String clieClasifNpcv6) {
		this.clieClasifNpcv6 = clieClasifNpcv6;
	}

	public boolean isClieHabilCcClie() {
		return this.clieHabilCcClie;
	}

	public void setClieHabilCcClie(boolean clieHabilCcClie) {
		this.clieHabilCcClie = clieHabilCcClie;
	}

	public String getClieClienteExt() {
		return this.clieClienteExt;
	}

	public void setClieClienteExt(String clieClienteExt) {
		this.clieClienteExt = clieClienteExt;
	}

	public Date getClieFechaProxGc() {
		return this.clieFechaProxGc;
	}

	public void setClieFechaProxGc(Date clieFechaProxGc) {
		this.clieFechaProxGc = clieFechaProxGc;
	}

	public String getClieProxGesCobr() {
		return this.clieProxGesCobr;
	}

	public void setClieProxGesCobr(String clieProxGesCobr) {
		this.clieProxGesCobr = clieProxGesCobr;
	}

	public short getClieAcctGencbpte() {
		return this.clieAcctGencbpte;
	}

	public void setClieAcctGencbpte(short clieAcctGencbpte) {
		this.clieAcctGencbpte = clieAcctGencbpte;
	}

	public String getClieNodoOrigen() {
		return this.clieNodoOrigen;
	}

	public void setClieNodoOrigen(String clieNodoOrigen) {
		this.clieNodoOrigen = clieNodoOrigen;
	}

	public String getClieMunicipio() {
		return this.clieMunicipio;
	}

	public void setClieMunicipio(String clieMunicipio) {
		this.clieMunicipio = clieMunicipio;
	}

	public boolean isClieInfTabasto() {
		return this.clieInfTabasto;
	}

	public void setClieInfTabasto(boolean clieInfTabasto) {
		this.clieInfTabasto = clieInfTabasto;
	}

	public boolean isClieCobroCorrel() {
		return this.clieCobroCorrel;
	}

	public void setClieCobroCorrel(boolean clieCobroCorrel) {
		this.clieCobroCorrel = clieCobroCorrel;
	}

	public String getClieVehiculo() {
		return this.clieVehiculo;
	}

	public void setClieVehiculo(String clieVehiculo) {
		this.clieVehiculo = clieVehiculo;
	}

	public String getClieDistribuidor() {
		return this.clieDistribuidor;
	}

	public void setClieDistribuidor(String clieDistribuidor) {
		this.clieDistribuidor = clieDistribuidor;
	}

	public String getClieZonaDistrib() {
		return this.clieZonaDistrib;
	}

	public void setClieZonaDistrib(String clieZonaDistrib) {
		this.clieZonaDistrib = clieZonaDistrib;
	}

	public String getClieCalle() {
		return this.clieCalle;
	}

	public void setClieCalle(String clieCalle) {
		this.clieCalle = clieCalle;
	}

	public Integer getClieNroCalle() {
		return this.clieNroCalle;
	}

	public void setClieNroCalle(Integer clieNroCalle) {
		this.clieNroCalle = clieNroCalle;
	}

	public String getCliePiso() {
		return this.cliePiso;
	}

	public void setCliePiso(String cliePiso) {
		this.cliePiso = cliePiso;
	}

	public String getClieDepto() {
		return this.clieDepto;
	}

	public void setClieDepto(String clieDepto) {
		this.clieDepto = clieDepto;
	}

	public String getClieBarrio() {
		return this.clieBarrio;
	}

	public void setClieBarrio(String clieBarrio) {
		this.clieBarrio = clieBarrio;
	}

	public short getClieDiasgrAtrRc() {
		return this.clieDiasgrAtrRc;
	}

	public void setClieDiasgrAtrRc(short clieDiasgrAtrRc) {
		this.clieDiasgrAtrRc = clieDiasgrAtrRc;
	}

	public String getClieClasif5() {
		return this.clieClasif5;
	}

	public void setClieClasif5(String clieClasif5) {
		this.clieClasif5 = clieClasif5;
	}

	public String getClieClasif6() {
		return this.clieClasif6;
	}

	public void setClieClasif6(String clieClasif6) {
		this.clieClasif6 = clieClasif6;
	}

	public String getClieClasif7() {
		return this.clieClasif7;
	}

	public void setClieClasif7(String clieClasif7) {
		this.clieClasif7 = clieClasif7;
	}

	public String getClieClasif8() {
		return this.clieClasif8;
	}

	public void setClieClasif8(String clieClasif8) {
		this.clieClasif8 = clieClasif8;
	}

	public String getClieClasif9() {
		return this.clieClasif9;
	}

	public void setClieClasif9(String clieClasif9) {
		this.clieClasif9 = clieClasif9;
	}

	public String getClieSitioWeb() {
		return this.clieSitioWeb;
	}

	public void setClieSitioWeb(String clieSitioWeb) {
		this.clieSitioWeb = clieSitioWeb;
	}

//	public Serializable getClieDescripActiv() {
//		return this.clieDescripActiv;
//	}
//
//	public void setClieDescripActiv(Serializable clieDescripActiv) {
//		this.clieDescripActiv = clieDescripActiv;
//	}

	public Integer getClieFactAnual() {
		return this.clieFactAnual;
	}

	public void setClieFactAnual(Integer clieFactAnual) {
		this.clieFactAnual = clieFactAnual;
	}

	public Integer getClieCantEmplead() {
		return this.clieCantEmplead;
	}

	public void setClieCantEmplead(Integer clieCantEmplead) {
		this.clieCantEmplead = clieCantEmplead;
	}

	public String getClieEcmEmail() {
		return this.clieEcmEmail;
	}

	public void setClieEcmEmail(String clieEcmEmail) {
		this.clieEcmEmail = clieEcmEmail;
	}

	public String getClieEcmAsunto() {
		return this.clieEcmAsunto;
	}

	public void setClieEcmAsunto(String clieEcmAsunto) {
		this.clieEcmAsunto = clieEcmAsunto;
	}

//	public Serializable getClieEcmCuerpo() {
//		return this.clieEcmCuerpo;
//	}
//
//	public void setClieEcmCuerpo(Serializable clieEcmCuerpo) {
//		this.clieEcmCuerpo = clieEcmCuerpo;
//	}
//
//	public Serializable getClieObservacionProxGesCobr() {
//		return this.clieObservacionProxGesCobr;
//	}
//
//	public void setClieObservacionProxGesCobr(Serializable clieObservacionProxGesCobr) {
//		this.clieObservacionProxGesCobr = clieObservacionProxGesCobr;
//	}

	public String getClieCodCalle() {
		return this.clieCodCalle;
	}

	public void setClieCodCalle(String clieCodCalle) {
		this.clieCodCalle = clieCodCalle;
	}

	public String getClieErmEmail() {
		return this.clieErmEmail;
	}

	public void setClieErmEmail(String clieErmEmail) {
		this.clieErmEmail = clieErmEmail;
	}

	public String getClieErmAsunto() {
		return this.clieErmAsunto;
	}

	public void setClieErmAsunto(String clieErmAsunto) {
		this.clieErmAsunto = clieErmAsunto;
	}

	public Serializable getClieErmCuerpo() {
		return this.clieErmCuerpo;
	}

	public void setClieErmCuerpo(Serializable clieErmCuerpo) {
		this.clieErmCuerpo = clieErmCuerpo;
	}

	public BigDecimal getClieTasaMensInteres() {
		return this.clieTasaMensInteres;
	}

	public void setClieTasaMensInteres(BigDecimal clieTasaMensInteres) {
		this.clieTasaMensInteres = clieTasaMensInteres;
	}

	public Date getClieHoraProxGc() {
		return this.clieHoraProxGc;
	}

	public void setClieHoraProxGc(Date clieHoraProxGc) {
		this.clieHoraProxGc = clieHoraProxGc;
	}

	public Short getClieNivelAccesoWeb() {
		return this.clieNivelAccesoWeb;
	}

	public void setClieNivelAccesoWeb(Short clieNivelAccesoWeb) {
		this.clieNivelAccesoWeb = clieNivelAccesoWeb;
	}

	public byte getClieBloqueadoReservas() {
		return this.clieBloqueadoReservas;
	}

	public void setClieBloqueadoReservas(byte clieBloqueadoReservas) {
		this.clieBloqueadoReservas = clieBloqueadoReservas;
	}

	public String getClieLogotipoNomOri() {
		return this.clieLogotipoNomOri;
	}

	public void setClieLogotipoNomOri(String clieLogotipoNomOri) {
		this.clieLogotipoNomOri = clieLogotipoNomOri;
	}

	public String getClieLogotipoNomAlmac() {
		return this.clieLogotipoNomAlmac;
	}

	public void setClieLogotipoNomAlmac(String clieLogotipoNomAlmac) {
		this.clieLogotipoNomAlmac = clieLogotipoNomAlmac;
	}

}
